/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



/********************************************************************** 
 
    CLASE: {@link MenuPrincipal}
    
    AUTOR: Mario Lopez Duran

 **********************************************************************/
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMenuVentas = new javax.swing.JButton();
        btMenuClientes = new javax.swing.JButton();
        btMenuPedidos = new javax.swing.JButton();
        btMenuInventario = new javax.swing.JButton();
        btMenuSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        btMenuVentas.setBackground(new java.awt.Color(0, 204, 102));
        btMenuVentas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/Ventas.png"))); // NOI18N
        btMenuVentas.setText("Ventas");
        btMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuVentasActionPerformed(evt);
            }
        });

        btMenuClientes.setBackground(new java.awt.Color(51, 51, 255));
        btMenuClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/cliente.jpg"))); // NOI18N
        btMenuClientes.setText("Clientes");
        btMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuClientesActionPerformed(evt);
            }
        });

        btMenuPedidos.setBackground(new java.awt.Color(255, 51, 51));
        btMenuPedidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMenuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/pedidos.png"))); // NOI18N
        btMenuPedidos.setText("Pedidos");
        btMenuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuPedidosActionPerformed(evt);
            }
        });

        btMenuInventario.setBackground(new java.awt.Color(204, 0, 204));
        btMenuInventario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/icon_inventario.gif"))); // NOI18N
        btMenuInventario.setText("Inventario");
        btMenuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuInventarioActionPerformed(evt);
            }
        });

        btMenuSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMenuSalir.setText("Salir");
        btMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btMenuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMenuClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenuVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenuPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenuInventario))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btMenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btMenuPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMenuInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btMenuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuVentasActionPerformed
        this.dispose();
        vistaRegistrarVentas registradorVentas = new vistaRegistrarVentas();
        registradorVentas.setVisible(true);
    }//GEN-LAST:event_btMenuVentasActionPerformed

    private void btMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuClientesActionPerformed
        this.dispose();
        new vistaClientes().setVisible(true);
    }//GEN-LAST:event_btMenuClientesActionPerformed

    private void btMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_btMenuSalirActionPerformed

    private void btMenuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuPedidosActionPerformed
        // TODO add your handling code here:
       this.dispose();
        VistaPedidos vistaPedidos = new VistaPedidos();
        vistaPedidos.setVisible(true);
    }//GEN-LAST:event_btMenuPedidosActionPerformed

    private void btMenuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuInventarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        vistaInventario inventario = new vistaInventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_btMenuInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMenuClientes;
    private javax.swing.JButton btMenuInventario;
    private javax.swing.JButton btMenuPedidos;
    private javax.swing.JButton btMenuSalir;
    private javax.swing.JButton btMenuVentas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
